### ISSUE TITLE
First edits

### ISSUE THREAD

**Issue by tram-nguyen-n** [ccb-hms/ProteinGymR#1]
Hi @lgeistlinger would you mind giving the package a first-look and provide me with any edits you may have please?

**Comment by lgeistlinger** [comment]
Some more: 

- resources from ProteinGym, generated by Notin et al. [2023](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10723403/) -> ProteinGym ([Notin et al., 2023](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10723403/))
- Currently, this package provides -> The package provides
- (DMS) scores generated from single substitution mutations across 216 assays -> (DMS) scores from 216 assays measuring the impact of all possible amino acid substitutions across xx proteins, and  
- predicted AlphaMissense pathogenicity scores for ~1.6M substitutions matching those in the ProteinGym DMS data -> AlphaMissense pathogenicity scores for the ~1.6 M substitutions in the ProteinGym DMS data

**Comment by lgeistlinger** [comment]
A couple of notes on the `DESCRIPTION` file:

**Comment by lgeistlinger** [comment]
- `Title`: Programmatic access **to** ProteinGym datasets in **R/Bioconductor**
- `Version`: change to `0.99.0` to comply with Bioc package versioning scheme
- `Description`: match with description in the README
- some additional [BiocViews](https://www.bioconductor.org/packages/release/BiocViews.html) to consider: CellCulture, SequencingData

**Comment by lgeistlinger** [comment]
Add installation instructions to README (for the moment only describe how to install the package from github) ...

**Comment by lgeistlinger** [comment]
There is currently no vignette. Bioconductor packages are required to have a vignette.

**Comment by lgeistlinger** [comment]
Functions names are supposed to start lower case according to Bioconductor coding style. Consider renaming:

- AlphaMissense_scores -> am_scores
- DMS_substitutions -> dms_scores

**Comment by lgeistlinger** [comment]
Function name mismatch in [DMS_substitutions.R](https://github.com/ccb-hms/ProteinGymR/blob/0c1ddac0ec508f354b464080993cacf9998f6bb7/R/DMS_substitutions.R#L42C1-L47C49):

- Function name in function definition: DMS_substitutions
- Function name in example: ProteinGym_DMS_subs

**Comment by lgeistlinger** [comment]
`DMS_substitutions` currently returns a `list` of `tibble`s. `AlphaMissense_scores` returns an ordinary `data.frame`. Is there a strong argument for returning tibble and thus requiring the extra dependency. My preference would be for `DMS_substitutions` to return a `list` of ordinary `data.frame`s.

**Comment by lgeistlinger** [comment]
#' Load AlphaMissense scores for ProteinGym variants -> #' AlphaMissense scores for ProteinGym variants
#' Load ProteinGym DMS Substitution Scores -> ProteinGym Deep Mutational Scanning (DMS) Scores

**Comment by lgeistlinger** [comment]
You don't need to link the bulky reference in details [here](https://github.com/ccb-hms/ProteinGymR/blob/0c1ddac0ec508f354b464080993cacf9998f6bb7/R/DMS_substitutions.R#L12). Just say: "See references."

Same [here](https://github.com/ccb-hms/ProteinGymR/blob/0c1ddac0ec508f354b464080993cacf9998f6bb7/R/AlphaMissense_scores.R#L13).

**Comment by tram-nguyen-n** [comment]
Thanks for the edits @lgeistlinger! Incorporated them all. 

For this comment:

> Functions names are supposed to start lower case according to Bioconductor coding style. Consider renaming:
> 
> * AlphaMissense_scores -> am_scores
> * DMS_substitutions -> dms_scores

I changed it to `dms_substitutions` to distinguish it from the DMS indel scores that are provided in ProteinGym too. 

I can overwrite the list object on Azure to be data.frames instead of tibbles after Aaron and Pascal's edits.

**Comment by tram-nguyen-n** [comment]
changes incorporated
