### ISSUE TITLE
models and metrics

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/ProteinGymR#14]
I think it would be good to bring in some more intuition on the models and the metrics from the proteingym paper. consider for example figure 1 of the paper that groups models into 4 categories (alignment-based, protein language models, etc.) and that groups metrics into 2 categories (fitness prediction, protein design).

Also some intuition on how metrics are calculated would be good (likely somewhere described in the Methods section of the paper). I think spearman correlation and AUC are well known, but I don't think it is very clear what the other three metrics are about.

**Comment by tram-nguyen-n** [comment]
Included much more detail with commit: 742c2efc05b85ee37a419611f573b2a7ece7df61
