### ISSUE TITLE
vignette: DMS visualization

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/ProteinGymR#2]
A good way to provide the user with some better understanding of the DMS data would be to create a heatmap as in Figure 2 of this [DMS review article](https://www.nature.com/articles/nmeth.3027):

<img width="684" alt="Screenshot 2024-08-14 at 4 29 12 PM" src="https://github.com/user-attachments/assets/f14b34e9-6e38-46cb-8d45-b800087acecb">

**Comment by lgeistlinger** [comment]
A great package for creating heatmaps is the [CompexHeatmap](https://bioconductor.org/packages/ComplexHeatmap) package.

**Comment by lgeistlinger** [comment]
It will also be good to say a couple more words about what DMS is and refer the user to this [DMS review article](https://www.nature.com/articles/nmeth.3027) for additional information.

**Comment by tram-nguyen-n** [comment]
Added!
